version: '3'

services:
  bdd:
    container_name: projetsortir
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: syo
      MYSQL_DATABASE: sortirbdd
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - bdd-data:/var/lib/mysql

volumes:
  bdd-data: